### ISSUE TITLE
Library doesn't seem to work with go modules (go1.11)

### ISSUE THREAD

**Issue by bmeh** [niubaoshu/gotiny#1]
Hello.

Your library doesn't work with go modules, as is demonstrated below:

To reproduce:

```
$ go get github.com/niubaoshu/gotiny
$ cp -r $GOPATH/src/github.com/niubaoshu/gotiny/example /tmp
$ mv /tmp/example/helloworld.go /tmp/example/main.go
$ go mod init main
$ go mod vendor
$ go build
or
$ go build -mod vendor
```

Output from `go build`:
```
# main
./main.go:12:2: undefined: gotiny.Unmarshal
./main.go:12:19: undefined: gotiny.Marshal
./main.go:19:5: dec.DecodeValue undefined (type *gotiny.Decoder has no field or method DecodeValue)
./main.go:19:21: enc.EncodeValue undefined (type *gotiny.Encoder has no field or method EncodeValue)
```

**Comment by bmeh** [comment]
All right, I figured out the problem. It's because it `go mod init` and `go mod vendor` appends `require github.com/niubaoshu/gotiny v0.0.2`, and this version is quite outdated. Not sure why it does that by default, but perhaps you could make a new release, so it would use v0.0.3 which would have all the missing functions. For now, I will edit it manually I guess.

**Comment by bmeh** [comment]
All right, I figured out the problem. It's because `go mod init` and `go mod vendor` appends `require github.com/niubaoshu/gotiny v0.0.2`, and this version is quite outdated. Not sure why it does that by default, but perhaps you could make a new release, so it would use `v0.0.3` which would have all the missing functions. For now, I will edit it manually I guess.

Replacing `v0.0.2` to `master` solves the issue, it changes it to `v0.0.3-0.20180825113500-8e92c8e02742` actually. Everything works this way.
